@extends('layout.app')
@section('content')
    <div class="container mt-3">
        <h2>Data Siswa RPL</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nama</th>
                    <th>NIS</th>
                    <th>Alamat</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>nama</td>
                    <td>32434</td>
                    <td>Nglinggis</td>
                </tr>
                <tr>
                    <td>nama</td>
                    <td>32332</td>
                    <td>Nglinggis</td>
                </tr>
                <tr>
                    <td>nama</td>
                    <td>32332</td>
                    <td>nglinggis</td>
                </tr>
                <tr>
                    <td>nama</td>
                    <td>32332</td>
                    <td>nglinggis</td>
                </tr>
                <tr>
                    <td>nama</td>
                    <td>32332</td>
                    <td>nglinggis</td>
                </tr>
                <tr>
                    <td>nama</td>
                    <td>32332</td>
                    <td>nglinggis</td>
                </tr>
                <tr>
                    <td>nama</td>
                    <td>32332</td>
                    <td>nglinggis</td>
                </tr>
                <tr>
                    <td>nama</td>
                    <td>32332</td>
                    <td>nglinggis</td>
                </tr>
                <tr>
                    <td>nama</td>
                    <td>32332</td>
                    <td>nglinggis</td>
                </tr>
                <tr>
                    <td>nama</td>
                    <td>32332</td>
                    <td>nglinggis</td>
                </tr>
            </tbody>
        </table>
    </div>
    <br><br>
@endsection
